windows_container:
  image: cirrusci/windowsservercore:cmake

windows_task:
  script:
    - cd "c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC"
    - vcvarsall x86
    - cd C:/Users/ContainerAdministrator/AppData/Local/Temp/cirrus-ci-build
    - cl /EHsc test.c
    - mklink /j my_junction c:/windows
    - mklink /d my_symlink c:/windows
    - test.exe
