windows_container:
  image: cirrusci/windowsservercore:cmake

windows_task:
  script:
    - cd "c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC"
    - vcvarsall x86
    - cd C:/Users/ContainerAdministrator/AppData/Local/Temp/cirrus-ci-build
    - cl /EHsc test.c
    - mklink /j good_junction "c:\\windows"
    - mklink /d good_symlink "c:\\windows"
    - mklink /j bad_junction "c:\\does not exist"
    - mklink /d bad_symlink "c:\\windows"
    - test.exe
